/**
 * ADULT — RADIANT variant (≥80 average care score over 14-day rolling window).
 * Size 22×22. Shiny halo pixels (n/lilac) around antennae, crown detail,
 * long lashes, perfectly clean outline, bright pink saturated.
 */

import type { SpriteFrame } from '../sprites/palette';
import { PALETTE } from '../sprites/palette';

export const RADIANT_FRAME_W = 22;
export const RADIANT_FRAME_H = 22;

/* ======== Base idle ======== */
const radBase0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSSwkSSSSkwSSSk..',
  '.kSSSSSSSkkkkkSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Happy */
const radHappy0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSwwwwwwwwwwwwSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radHappy1: SpriteFrame = [
  '......................',
  '........n..n..........',
  '.......nWWnWn.........',
  '.......kWwkWWn........',
  '......kkSSkSSnn.......',
  '.....kkSSSSSSnkk......',
  '....kSWWSSSSSSWk......',
  '...kSSSkkkkkkSSSk.....',
  '..kSSSSSSSSSSSSSSk....',
  '..kSSSSSppSSppSSSk....',
  '.kSSSSS^^SSSS^^SSSk...',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kSSSwwwwwwwwwwwwSk...',
  '.kSSSSSSdSSSSSSdSSk...',
  '.kSSdddddddddddddk....',
  '..kkSSddddSSSSdddk....',
  '...kkk.SSSSSSSS.k.....',
  '.....kkSS....SSk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Eating */
const radEat0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSkkkkkkkkkkkkSSSk.',
  '.kSSSSwWWWWWWWWwSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radEat1: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSSSkkkkkkkkSSSSSk.',
  '.kSSSSSwwSSSSwwSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Playing */
const radPlay0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSwwSSwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSdddSSSSdddSSSSk.',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kkddddSSSSSSddddkk...',
  '..kk..............kk..',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radPlay1: SpriteFrame = [
  '......................',
  '......................',
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '..kSSSSS^^SSS^^SSSSk..',
  '.kSSSSSSSSwwSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSdddSSSSSSdddSSSk..',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kkddddddSSdddddddkk..',
  '..kk..............kk..',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sleep */
const radSleep0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSSSSSSSSSSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSS--SSSSSS--SSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radSleep1: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSSSSSSSSSSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSS==SSSSSS==SSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Hungry */
const radHungry0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSvvSSSSvvSSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSwwwwSSSSwwwwSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radHungry1: SpriteFrame = [
  '......................',
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '..kSSSSS^^SSSS^^SSSk..',
  '..kSSSSvvSSSSvvSSSSk..',
  '.kSSSSwwwwwwwwwwwwSSk.',
  '.kSSSwwwwSSSSwwwwSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sad */
const radSad0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSxxSSSSSSxxSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSSSwwwSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radSad1: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '.bkSSSSSSSSSSSSSSSSk..',
  'bbkSSSSSppSSppSSSSSk..',
  'bb.kSSSxxSSSSxxSSSk...',
  '...kSSSSSSSSSSSSSSSk..',
  '.kSSSSwwwSSSSwwwSSSk..',
  '.kSSSSSdSSSSSSdSSSSk..',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sick */
const radSick0: SpriteFrame = [
  '......................',
  '........nn............',
  '.......nWWn...........',
  '.......kWwk...........',
  '......kkSSkk..........',
  '....kkSSSSSSkk........',
  '...kSWWSSSSSSWk.......',
  '..kSSSkkkkkkSSSk......',
  '.kSSSSSSSSSSSSSSk.....',
  '.kSSSSSppSSppSSSSk....',
  '.kSSSSxxSSSSxxSSSk....',
  'kSSSSSSSSwwwwSSSSSk...',
  'kSSSSSSwSwwSwSSSSSk...',
  'kSSSSSSdSSSSdSSSSSk...',
  '.kSSdddddddddddddSk...',
  '.kkSSddddSSSSddddkk...',
  '..kkk.SSSSSSSS.kkk....',
  '....kkSS....SSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radSick1: SpriteFrame = [
  '......................',
  '............nn........',
  '...........nWWn.......',
  '...........kWwk.......',
  '..........kkSSkk......',
  '........kkSSSSSSkk....',
  '.......kSWWSSSSSSWk...',
  '......kSSSkkkkkkSSSk..',
  '.....kSSSSSSSSSSSSk...',
  '.....kSSSSppSSppSSSk..',
  '.....kSSSxxSSSxxSSSk..',
  '....kSSSSSSwwwwSSSSSk.',
  '....kSSSSwSwwSwSSSSSk.',
  '....kSSSSdSSSSdSSSSSk.',
  '....kSSdddddddddddSk..',
  '....kkSSddddSSddddkk..',
  '.....kkk.SSSSSS.kkk...',
  '.......kkSS..SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Dirty */
const radDirty0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSScSSSck......',
  '.....kSWcSSSScSWSk....',
  '....kSSSWkcScWSSSk....',
  '...kSSSSSSSSSSSScSk...',
  '..kSSSSSppccppSSSSSk..',
  '..kSSSSwkSSccSSkwSSk..',
  '.kSSSSSSccSSccSSSSSSk.',
  '.kSSSSSScSScSSSSSSSSk.',
  '.kSSSSSdcccccddSSSSk..',
  '.kSSdddcdccdddcdcdSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radDirty1: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSck......',
  '.....kSWWSSSSSWScc....',
  '....kSSSWkcSSkWSSc....',
  '.ckSSSSSSSSSSSSSSSk...',
  '..kSSSSSppSSppSScck...',
  '..kSSSSwkSSSSSkwcSk...',
  '.kSSSSSSccSSccSSSScSk.',
  '.kSSSScSSSScSSSSSSSSk.',
  '.kSScSSdScSScSccdSSk..',
  '.kSSdddddddddddddcSk..',
  '..kkSSdddcSSSddddkkc..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Pet */
const radPet0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSPPPPSSSSSPPPPSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radPet1: SpriteFrame = [
  '......................',
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '..kSPPPPSSSSSPPPPSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Refuse */
const radRefuse0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSXXSSXXSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSkkSSSSSSSSSSkkSSk.',
  '.kSSwwwwwwwwwwwwwwSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radRefuse1: SpriteFrame = [
  '......................',
  '..nn..................',
  '.nWWn.................',
  '.kWwk.................',
  'kkSSkk................',
  'kSSSSSSkk.............',
  'kSWWSSSSWSk...........',
  'kSSSXXSSXXSk..........',
  'kSSSSSSSSSSSSk........',
  'kSSSSppSSppSSk........',
  'kSSSSwkSSSSkwSSk......',
  'kSSkkSSSSSSSSkkSSk....',
  'kSwwwwwwwwwwwwwwSk....',
  '.kSSSSdSSSSSSdSSSk....',
  '.kSSddddddddddddSk....',
  '..kkSSddddSSSSddkk....',
  '...kkk.SSSSSSSS.kk....',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Clean */
const radClean0: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kbBk.........',
  '........kbbBbk........',
  '......kkbbSSbbkk......',
  '.....kbBWSSSSBWbk....',
  '....kbBbWkSSkWbBb k...',
  '...kbbbbbbbbbbbbbbk...',
  '..kSSSSSSbbSSbbSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSSSSSkkkkkSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const radClean1: SpriteFrame = [
  '......................',
  '..........nn..........',
  '.........nWWn.........',
  '.........kbBk.........',
  '.......bbkbbBkbb......',
  '......bbkbbSSbkbbbb...',
  '.....kbBWSbbbbSBWbk...',
  '....kBBbWkSSkWbBBk....',
  '...kbbbbbbbbbbbbbbk...',
  '..kSSSSbbSSbbSSSSSk...',
  '.kSSSSSwwSSSSwwSSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSSSSSdSSSSk.',
  '.kSSddddddddddddddSk..',
  '..kkSSddddSSSSddddkk..',
  '...kkk.SSSSSSSS.kkk...',
  '.....kkSS....SSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* ================== animations ==================== */

export type RadiantAnimationName =
  | 'idle'
  | 'happy'
  | 'eating'
  | 'playing'
  | 'sleeping'
  | 'hungry'
  | 'sad'
  | 'sick'
  | 'dirty'
  | 'pet'
  | 'refuse'
  | 'clean'
  | 'blink';

export interface RadiantAnimation {
  readonly frames: readonly SpriteFrame[];
  readonly frameTime: number;
}

export const radiantAnimations: Record<RadiantAnimationName, RadiantAnimation> = {
  idle:     { frames: [radBase0], frameTime: 0.5 },
  happy:    { frames: [radHappy0, radHappy1], frameTime: 0.22 },
  eating:   { frames: [radEat0, radEat1], frameTime: 0.18 },
  playing:  { frames: [radPlay0, radPlay1, radPlay0, radPlay1], frameTime: 0.18 },
  sleeping: { frames: [radSleep0, radSleep1], frameTime: 0.6 },
  hungry:   { frames: [radHungry0, radHungry1], frameTime: 0.35 },
  sad:      { frames: [radSad0, radSad1], frameTime: 0.5 },
  sick:     { frames: [radSick0, radSick1], frameTime: 0.4 },
  dirty:    { frames: [radDirty0, radDirty1], frameTime: 0.5 },
  pet:      { frames: [radPet0, radPet1], frameTime: 0.28 },
  refuse:   { frames: [radRefuse0, radRefuse1], frameTime: 0.2 },
  clean:    { frames: [radClean0, radClean1], frameTime: 0.3 },
  blink:    { frames: [radBase0], frameTime: 0.08 },
};

export const radiantEyeSlots: readonly {
  readonly x: number; readonly y: number; readonly w: number; readonly h: number;
}[] = [
  { x: 7,  y: 10, w: 2, h: 2 },
  { x: 13, y: 10, w: 2, h: 2 },
];

void PALETTE;
