/**
 * ADULT — SCRUFFY variant (<50 average care).
 * 22×22. Messy tufts sticking up, bent antenna, scruffy non-smooth outline,
 * a few permanent brown (c) patches, one floppy ear/tuft.
 */

import type { SpriteFrame } from '../sprites/palette';
import { PALETTE } from '../sprites/palette';

export const SCRUFFY_FRAME_W = 22;
export const SCRUFFY_FRAME_H = 22;

/* ===== Base idle ===== */
const scBase0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSWkSSSSkWSSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSwkSSSSSSkwcSSk.',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSScSSSSSSSSSScSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Happy */
const scHappy0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccS^^SSSS^^^wcSSk.',
  '.kSSSSSSwwwwwwSSSSk..',
  '.kSScSSSSSSSSSScSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scHappy1: SpriteFrame = [
  '......................',
  '.....k.....kk........',
  '....kWk..kkkkk.......',
  '...kkSSkkWWwkk.......',
  '..kSScSSSSSSSSkkk....',
  '.kSWWSSSSSScSWWSkk...',
  '.kSSSkkkkkkkkSSSSk...',
  'kSSScccSSSccSSSSSk...',
  'kSSSSSSppSSppSSSSk...',
  '.kSScc^^SSSS^^wcSSk..',
  '.kSSSwwwwwwwwwwSSk...',
  '.kSScSSSSSSSSSScSk...',
  '.kSSSSSSdSSddSSdSSk..',
  '.kSSdddSdddSdddSddSk.',
  '..kkSSdddddSSddddk...',
  '...kkSSSSccSSSSkkk...',
  '....kk..c..c..Skk....',
  '......kk..k..k.......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Eat */
const scEat0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSWkSSSSkWSSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSwkSSSSSSkwcSSk.',
  '.kSSkkkkkkkkkkkkSSk..',
  '.kSSwWWWWWWWWWWwSSk..',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scEat1: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSWkSSSSkWSSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSwkSSSSSSkwcSSk.',
  '.kSSSSkkkkkkkkSSSSk..',
  '.kSSSSwwSSwwwwSSSSk..',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Play */
const scPlay0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccS^^SSSS^^^wcSSk.',
  '.kSSSSSSwwwwwwSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSdddSdddSdddSSSSk.',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kkddddSSSSSSSddddk..',
  '..kk...............k.',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scPlay1: SpriteFrame = [
  '......................',
  '......................',
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkSSSk....',
  'kSSccc^^SSccSSSSSk...',
  '.kSSccS^^SSS^^wcSSk..',
  '.kSSSSSwwwwwwwwSSk...',
  '.kdddSSSSSSSSSSSdddk.',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kkddddddddddddddkk..',
  '..kk..............k..',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sleep */
const scSleep0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSSSSSSSSSSSSSSk..',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSS--SSSSSSSS--cSSk.',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scSleep1: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSSSSSSSSSSSSSSk..',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSS==SSSSSSSS==cSSk.',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Hungry */
const scHungry0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSvvSSSSvv^wcSSk.',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSSwwwwwwwwwwwwSSk..',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scHungry1: SpriteFrame = [
  '......................',
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSvvSSSSvvppSSk..',
  '.kSSSwwwwwwwwwwwwSk..',
  '.kSSSwwwwwSSSSwwwwk..',
  '.kSSSSSSdSSddSSdSSk..',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sad */
const scSad0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSxxSSSSxx^wcSSk.',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSSSSwwwSSSSwwwSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scSad1: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'bkSSScccSSSccSSSSSk..',
  'bbkSSSSSppSSppSSSSk..',
  'bb.kSSSxxSSSSxxcSSk..',
  '...kSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSSSwwwSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sick */
const scSick0: SpriteFrame = [
  '......................',
  '......k..kk..........',
  '.....kWkWWwk.........',
  '....kkSSkk...........',
  '..kkSScSSSSSSSSkk....',
  '.kSWWSSSSSScSWWSk....',
  'kSSSWkSSSSkWSSSSk....',
  '.kSSScccSSSccSSSSk...',
  'kSSSSSSppSSppSSSSk...',
  '.kSSSxxSSSSxxcSSSk...',
  '.kSSSSSSwwwwSSSSSk...',
  '.kSSSSwSwwSwSSSScSk..',
  '.kSSSSSSdSSddSSdSSk..',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scSick1: SpriteFrame = [
  '......................',
  '..........kk.k.......',
  '.........WWwkWk......',
  '........kkkkSSkk.....',
  '......kkSSSSSScSSkk..',
  '.....kSWWScSSSSSWWSk.',
  '....kSSWkSSSSkWSSSk..',
  '....kSSccSScccSSSSSk.',
  '...kSSSSppSSppSSSSk..',
  '...kSxxSSSSSSxxcSSk..',
  '..kSSSSSSwwwwSSSSSk..',
  '..kSSSwSwwSwSSSScSk..',
  '..kSSSSSSdSSdSSSSSk..',
  '..kSSdddSdddSdddSSk..',
  '..kkSSdddSSSSdddkk...',
  '...kkSSSSccSSSSkk....',
  '....kk..c..c..Skk....',
  '......kk..k..k.k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Dirty — extra scruffy overlay since scruffy is already "c" patchy; add more */
const scDirty0: SpriteFrame = [
  '......................',
  '......k..c..k........',
  '.....kWk..kkkk.......',
  '....kkSSckcWWwk......',
  '...kSScSSSccSSSkk....',
  '..kSWWScSScSSWWSck...',
  '.kSSSWkScccWSSSSck...',
  'kSSScccSSSccccccSSk..',
  '.kSSScccppSSppccSSk..',
  'kSSccSwkccccSSkwcSSk.',
  '.kSSSSSSccccccccSSk..',
  '.kSScSSccccccccSScSk.',
  '.kSSccSSdccccddccSk..',
  '.kSSddddcddddcddddSk.',
  '.kkSSSddcddccddddkk..',
  '..kkkSSccccccSSSkkk..',
  '...kkk.cc.cc.c.Skkk..',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scDirty1: SpriteFrame = [
  '......................',
  '......k.c...k........',
  '.....kWkk.ckkk.......',
  '....kkSSckWWcck......',
  '...kSScSSScSScckk....',
  '..kSWWSSSSScSWWScc...',
  '.kSSSWkcSSckWSSSSkcc.',
  'kSSScccSSccSSSccSSck.',
  '.kSSSSSSppccppSSSSckc',
  'kSSccSwkcSSSSkwccSSk.',
  '.kSSSSSSccccccccckk..',
  '.kccccSSSSSSSSccccSk.',
  '.kccccSSdSSccddccSSk.',
  '.kSSdddddcdccddddcSk.',
  '.kkSSSddddSddddddkkc.',
  '..kkcSScccccccccSkkc.',
  '...kkc.cc.cc.ccSkk...',
  '.....kkcckcck.k......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Pet */
const scPet0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSPPPPSSSSSPPPPSSk..',
  'kSSccS^^SSSS^^^wcSSk.',
  '.kSSSSSSwwwwwwSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scPet1: SpriteFrame = [
  '......................',
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSkkkkkkkkkSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSPPPPSSSSSPPPPSSk..',
  'kSSccS^^SSSS^^^wcSSk.',
  '.kSSSSSSwwwwwwSSSSk..',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Refuse */
const scRefuse0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkSSkkWWwk.......',
  '...kSScSSSSSSSSkk....',
  '..kSWWSSSSSScSWWSk...',
  '.kSSSXXSSSSXXSSSSk...',
  'kSSScccSSSccSSSSSSk..',
  '.kSSSSSSppSSppSSSSk..',
  'kSSccSwkSSSSSSkwcSSk.',
  '.kSSkkSSSSSSSSSSkkSk.',
  '.kSSwwwwwwwwwwwwwwSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scRefuse1: SpriteFrame = [
  '......................',
  '......................',
  '.kWk..................',
  'kkSSkk................',
  'SScSSSSSSkk...........',
  'SWWSSSSSScWS..........',
  'SSXXSSSSXXSS..........',
  'ScccSSccSSSSS.........',
  'SSSSSSppSSppSS........',
  'SwkSSSSSSkwSS.........',
  'kkSSSSSSSSSSkk........',
  'wwwwwwwwwwwwww........',
  'SSSSSSdSSddSSdSS......',
  'SSdddSdddSdddSdSk.....',
  'kSSSdddddSSddddkk.....',
  '.kkSSSSccSSSSSkkk.....',
  '..kk..c..c..Skkk......',
  '....kk..k..k.k........',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Clean */
const scClean0: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkbbkbbBbkk......',
  '...kbBbbbbbbbbbkk....',
  '..kbBWSbbbbbbbSWBbk..',
  '.kbBbWkbBbBbbBBbBbk..',
  'kbBbbbbbbbbbbbbbbbbk.',
  '.kSSSSbbSSbbSSbbSSk..',
  'kSSccSwkSSSSSSkwcSSk.',
  '.kSSSSSSkkkkkkkkSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];
const scClean1: SpriteFrame = [
  '......................',
  '......k.....k........',
  '.....kWk..kkkk.......',
  '....kkbbBbbBkk.......',
  '...kbbbbbbbbbbkk.....',
  '..kbBWbbbbbbbbSWBk...',
  '.kbBbWkbbbbbWbBbk....',
  'kbbbbbbbbbbbbbbbbbk..',
  '.kSSbbSSSSSSbbSSSSk..',
  'kSSccSwwSSSSwwccSSk..',
  '.kSSSSSSSSSSSSSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSk.',
  '.kSSdddSdddSdddSddSk.',
  '.kkSSSdddddSSddddkk..',
  '..kkkSSSSccSSSSSkkk..',
  '...kkk..c..c..Skkk...',
  '.....kk..k..k..k.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* ================== animations ==================== */

export type ScruffyAnimationName =
  | 'idle'
  | 'happy'
  | 'eating'
  | 'playing'
  | 'sleeping'
  | 'hungry'
  | 'sad'
  | 'sick'
  | 'dirty'
  | 'pet'
  | 'refuse'
  | 'clean'
  | 'blink';

export interface ScruffyAnimation {
  readonly frames: readonly SpriteFrame[];
  readonly frameTime: number;
}

export const scruffyAnimations: Record<ScruffyAnimationName, ScruffyAnimation> = {
  idle:     { frames: [scBase0], frameTime: 0.5 },
  happy:    { frames: [scHappy0, scHappy1], frameTime: 0.22 },
  eating:   { frames: [scEat0, scEat1], frameTime: 0.18 },
  playing:  { frames: [scPlay0, scPlay1, scPlay0, scPlay1], frameTime: 0.18 },
  sleeping: { frames: [scSleep0, scSleep1], frameTime: 0.6 },
  hungry:   { frames: [scHungry0, scHungry1], frameTime: 0.35 },
  sad:      { frames: [scSad0, scSad1], frameTime: 0.5 },
  sick:     { frames: [scSick0, scSick1], frameTime: 0.4 },
  dirty:    { frames: [scDirty0, scDirty1], frameTime: 0.5 },
  pet:      { frames: [scPet0, scPet1], frameTime: 0.28 },
  refuse:   { frames: [scRefuse0, scRefuse1], frameTime: 0.2 },
  clean:    { frames: [scClean0, scClean1], frameTime: 0.3 },
  blink:    { frames: [scBase0], frameTime: 0.08 },
};

export const scruffyEyeSlots: readonly {
  readonly x: number; readonly y: number; readonly w: number; readonly h: number;
}[] = [
  { x: 7,  y: 10, w: 2, h: 2 },
  { x: 13, y: 10, w: 2, h: 2 },
];

void PALETTE;
