/**
 * ADULT — CHILL variant (50-79 average care score).
 * 22×22. Relaxed rounded body with goatee tuft (d-rows extra), neutral
 * antennae, standard clean but unremarkable palette.
 */

import type { SpriteFrame } from '../sprites/palette';
import { PALETTE } from '../sprites/palette';

export const CHILL_FRAME_W = 22;
export const CHILL_FRAME_H = 22;

/* ===== Base ===== */
const chillBase0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Happy */
const chillHappy0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwwwwwwwwSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillHappy1: SpriteFrame = [
  '......................',
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSS^^SSS^^SSSSk..',
  '.kSSSSSSSSwwSSSSSSSk..',
  '.kSSSwwwwwwwwwwwwSSk..',
  '.kSSSSSSdSSddSSdSSSk..',
  '.kSSdddddddddSSdddSk..',
  '..kSSSdddddSSddddSk...',
  '...kkkSSSSSSSSSSSkk...',
  '....kkkSSSSSSSSSkk....',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Eat */
const chillEat0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSkkkkkkkkkkkkSSSk.',
  '.kSSSSwWWWWWWWWwSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillEat1: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSWkSSSSkWSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSSSkkkkkkkkSSSSSk.',
  '.kSSSSSwwSSSSwwSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Play */
const chillPlay0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSdddSSdddddSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kkSSdddddddddddddkk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkk...........kk..',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillPlay1: SpriteFrame = [
  '......................',
  '......................',
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSS^^SSS^^SSSk...',
  '..kSSSSSSSSwwSSSSSSk..',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kSSdddSSSSSSSSdddSk..',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kkdddddddddddddddkk..',
  '...kk..............k..',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sleep */
const chillSleep0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSSSSSSSSSSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSS--SSSSSS--SSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillSleep1: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSSSSSSSSSSSk...',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSS==SSSSSS==SSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Hungry */
const chillHungry0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSvvSSSSvvSSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSwwwwwwwwwwwwSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillHungry1: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '..kSSSSSS^^SSS^^SSSk..',
  '..kSSSSvvSSSSvvSSSSk..',
  '.kSSSSwwwwwwwwwwwwSk..',
  '.kSSSwwwwwwwwwwwwSk...',
  '.kSSSSSSSSSSSSSSSSSk..',
  '.kSSSSSSdSSddSSdSSSk..',
  '.kSSdddddddddSSdddSk..',
  '..kSSSdddddSSddddSk...',
  '...kkkSSSSSSSSSSSkk...',
  '....kkkSSSSSSSSSkk....',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sad */
const chillSad0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSxxSSSSSSxxSSSk..',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSSSwwwSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillSad1: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '.bkSSSSSSSSSSSSSSSSk..',
  'bbkSSSSSppSSppSSSSSk..',
  'bb.kSSSxxSSSSxxSSSk...',
  '...kSSSSSSSSSSSSSSSk..',
  '.kSSSSwwwSSSSwwwSSSk..',
  '.kSSSSSSdSSddSSdSSSk..',
  '.kSSdddddddddSSdddSk..',
  '..kSSSdddddSSddddSk...',
  '...kkkSSSSSSSSSSSkk...',
  '....kkkSSSSSSSSSkk....',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Sick */
const chillSick0: SpriteFrame = [
  '......................',
  '......................',
  '.......kWwk...........',
  '......kkSSkk..........',
  '....kkSSSSSSkk........',
  '...kSWWSSSSSSWSk......',
  '..kSSSWkSSSSkWSSk.....',
  '..kSSSSSSSSSSSSSSk....',
  '.kSSSSSSppSSppSSSSk...',
  '.kSSSxxSSSSSSxxSSSk...',
  '.kSSSSSSSSwwwwSSSSSk..',
  '.kSSSSSSwSwwSwSSSSSk..',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillSick1: SpriteFrame = [
  '......................',
  '......................',
  '...........kWwk.......',
  '..........kkSSkk......',
  '........kkSSSSSSkk....',
  '.......kSWWSSSSSSWSk..',
  '......kSSSWkSSSSkWSSk.',
  '.....kSSSSSSSSSSSSSSk.',
  '.....kSSSppSSSSppSSSk.',
  '.....kSxxSSSSSSxxSSSk.',
  '....kSSSSSSSwwwwSSSSk.',
  '....kSSSSwSwwSwSSSSSk.',
  '....kSSSSdSSddSSdSSSk.',
  '....kSdddddddSSddddSk.',
  '.....kSSddddSSddddSk..',
  '......kkSSSSSSSSSkk...',
  '.......kkSSSSSSSkk....',
  '.........kkSSSSkk.....',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Dirty */
const chillDirty0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSScSSSck......',
  '.....kSWcSSSScSWSk....',
  '....kSSSWkSSckWSSk....',
  '...kSSSSSSSSSSSScSk...',
  '..kSSSSSppccppSSSSSk..',
  '..kSScSwkSScSSkwcSk...',
  '.kSSSSSSccSSccSSSSSSk.',
  '.kSSSSSScSScSSSSSSSSk.',
  '.kSScSSdcccccdSScdSk..',
  '.kSSddddcdccdddcdSSk..',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillDirty1: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSck......',
  '.....kSWWSSSScWScc....',
  '....kSSSWkcSSkWSScc...',
  'ckSSSSSSSSSSSSSSSSk...',
  '.kSSSSSppcccppSSSSkc..',
  '..kSScSwkSSSSkwcSkc...',
  '.kSSSSScccccSSSSSScck.',
  '.kSSSScSSSSSScSSSScck.',
  '.kSSccSdccSScccdcSSk..',
  '.kSSdddcdccdddcdcdSk..',
  '..kSSSddddScddddSSk...',
  '...kkkSSSSSSSSSSSkk...',
  '....kkkSSSSSSSSSkkc...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Pet */
const chillPet0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSPPPPSSSSSPPPPSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillPet1: SpriteFrame = [
  '......................',
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSkkkkkkSSSk....',
  '..kSPPPPSSSSSPPPPSSk..',
  '..kSSSS^^SSSS^^SSSSk..',
  '.kSSSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Refuse */
const chillRefuse0: SpriteFrame = [
  '......................',
  '......................',
  '.........kWwk.........',
  '........kkSSkk........',
  '......kkSSSSSSkk......',
  '.....kSWWSSSSSSWSk....',
  '....kSSSXXSSXXSSSk....',
  '...kSSSSSSSSSSSSSSk...',
  '..kSSSSSSppSSppSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSkkSSSSSSSSSSkkSSk.',
  '.kSSwwwwwwwwwwwwwwSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillRefuse1: SpriteFrame = [
  '......................',
  '......................',
  '..kWwk................',
  '.kkSSkk...............',
  'kSSSSSSkk.............',
  'kSWWSSSSWSk...........',
  'kSSSXXSSXXSk..........',
  'kSSSSSSSSSSSSk........',
  'kSSSSppSSppSSk........',
  'kSSSSwkSSSSkwSSk......',
  'kSSkkSSSSSSSSkkSSk....',
  'kSwwwwwwwwwwwwwwSk....',
  '.kSSSSdSSddSSdSSSk....',
  '.kSSdddddSSSSddddk....',
  '.kSSdddSSSSSSddSSk....',
  '..kkkSSSSSSSSSSSkk....',
  '...kkkSSSSSSSSSkkk....',
  '.....kkSSSSSSkk.......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* Clean */
const chillClean0: SpriteFrame = [
  '......................',
  '......................',
  '.........kbBk.........',
  '........kbbbbk........',
  '......kbbbbbbbbkk.....',
  '.....kbBWSSSSSSWBk....',
  '....kbBbWkSSkWbBbk....',
  '...kbbbbbbbbbbbbbbk...',
  '..kSSSSSSbbSSbbSSSSk..',
  '..kSSSSwkSSSSSSkwSSk..',
  '.kSSSSSSSkkkkkSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];
const chillClean1: SpriteFrame = [
  '......................',
  '......................',
  '.........kbBk.........',
  '........kbbBb........',
  '......kbbbbbbbbkk.....',
  '.....kbBWSbbbbSBWbk...',
  '....kbBbWkSSkWbBBk....',
  '...kbbbbbbbbbbbbbbk...',
  '..kSSbbSSSSSSbbSSSSk..',
  '.kSSSSSwwSSSSwwSSSSk..',
  '.kSSSSSSSSkkkkSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSdSSddSSdSSSSk.',
  '.kSSdddddddddSSddddSk.',
  '..kSSSdddddSSddddSSk..',
  '...kkkSSSSSSSSSSSkkk..',
  '....kkkSSSSSSSSSkkk...',
  '......kkSSSSSSkk......',
  '......................',
  '......................',
  '......................',
  '......................',
];

/* ================== animations ==================== */

export type ChillAnimationName =
  | 'idle'
  | 'happy'
  | 'eating'
  | 'playing'
  | 'sleeping'
  | 'hungry'
  | 'sad'
  | 'sick'
  | 'dirty'
  | 'pet'
  | 'refuse'
  | 'clean'
  | 'blink';

export interface ChillAnimation {
  readonly frames: readonly SpriteFrame[];
  readonly frameTime: number;
}

export const chillAnimations: Record<ChillAnimationName, ChillAnimation> = {
  idle:     { frames: [chillBase0], frameTime: 0.5 },
  happy:    { frames: [chillHappy0, chillHappy1], frameTime: 0.22 },
  eating:   { frames: [chillEat0, chillEat1], frameTime: 0.18 },
  playing:  { frames: [chillPlay0, chillPlay1, chillPlay0, chillPlay1], frameTime: 0.18 },
  sleeping: { frames: [chillSleep0, chillSleep1], frameTime: 0.6 },
  hungry:   { frames: [chillHungry0, chillHungry1], frameTime: 0.35 },
  sad:      { frames: [chillSad0, chillSad1], frameTime: 0.5 },
  sick:     { frames: [chillSick0, chillSick1], frameTime: 0.4 },
  dirty:    { frames: [chillDirty0, chillDirty1], frameTime: 0.5 },
  pet:      { frames: [chillPet0, chillPet1], frameTime: 0.28 },
  refuse:   { frames: [chillRefuse0, chillRefuse1], frameTime: 0.2 },
  clean:    { frames: [chillClean0, chillClean1], frameTime: 0.3 },
  blink:    { frames: [chillBase0], frameTime: 0.08 },
};

export const chillEyeSlots: readonly {
  readonly x: number; readonly y: number; readonly w: number; readonly h: number;
}[] = [
  { x: 7,  y: 10, w: 2, h: 2 },
  { x: 13, y: 10, w: 2, h: 2 },
];

void PALETTE;
