/**
 * TEEN stage (day 3–6).
 * 20×20 frames — bigger body, teeny horns / antennae, little feet.
 * Still pink blob lineage; more details around face and limbs.
 */

import type { SpriteFrame } from '../sprites/palette';
import { PALETTE } from '../sprites/palette';

export const TEEN_FRAME_W = 20;
export const TEEN_FRAME_H = 20;

/* ======== teen idle base ======== */
const teenBase0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSWkSSkWSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSSwkSSSSkwSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Happy */
const teenHappy0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSS^^SSSS^^SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwwwwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenHappy1: SpriteFrame = [
  '....................',
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSppSSppSSSSk..',
  '..kSSS^^SSSS^^SSSk..',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwwwwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Eating chomp */
const teenEat0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSWkSSkWSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSkkkkkkkkkkSSSk.',
  '.kSSSSwWWWWWWwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenEat1: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSWkSSkWSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSSSkkkkkkSSSSSk.',
  '.kSSSSSwwSSwwSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Playing bounce */
const teenPlay0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSS^^SSSS^^SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSwwSSwwSSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSdddSSdddSSSSk.',
  '..kSSSSSSSSSSSSSSk..',
  '..kkkdddddSSdddddkk.',
  '...kkk..........kkk.',
  '....................',
  '....................',
  '....................',
];
const teenPlay1: SpriteFrame = [
  '....................',
  '....................',
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSppSSSSppSSSk..',
  '..kSS^^SSSS^^SSSSk..',
  '.kSSSSSSwwwwSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSdddSSSSSSdddSSk.',
  '..kkddddddddddddkk..',
  '...kkk..........kkk.',
  '....................',
  '....................',
  '....................',
];

/* Sleep */
const teenSleep0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSSSSSSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSS--SSSS--SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenSleep1: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSSSSSSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSS==SSSS==SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Hungry droopy */
const teenHungry0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSvvSSSSvvSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSwwwSSSSwwwSSSk.',
  '.kSSSSdSSSSSSdSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
];
const teenHungry1: SpriteFrame = [
  '....................',
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSvvSSSSvvSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Sad */
const teenSad0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSxxSSSSSSxxSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenSad1: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..bkSSSSSSSSSSSSSk..',
  '.bbkSSSppSSppSSSSSk.',
  '.bb.kSSxxSSSSxxSSk..',
  '...kSSSSSSSSSSSSSSk.',
  '.kSSSSwwwSSwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Sick wobble */
const teenSick0: SpriteFrame = [
  '....................',
  '........kk..........',
  '.......kWwk.........',
  '......kkSSkk........',
  '....kkSSSSSSkk......',
  '...kSWWSSSSWWSk.....',
  '..kSSSWkSSkWSSSk....',
  '..kSSSSSSSSSSSSSk...',
  '.kSSSSppSSppSSSSSk..',
  '.kSSSxxSSSSxxSSSSk..',
  '.kSSSSSSwwwwSSSSSSk.',
  '.kSSSSSwSwwSwSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '....................',
  '....................',
  '....................',
  '....................',
];
const teenSick1: SpriteFrame = [
  '....................',
  '..........kk........',
  '.........kWwk.......',
  '........kkSSkk......',
  '......kkSSSSSSkk....',
  '.....kSWWSSSSWWSk...',
  '....kSSSWkSSkWSSSk..',
  '...kSSSSSSSSSSSSSSk.',
  '...kSSSppSSppSSSSk..',
  '..kSSSxxSSSSxxSSSSk.',
  '..kSSSSSSwwwwSSSSSk.',
  '..kSSSSwSwwSwSSSSSk.',
  '..kSSSSdSSSSdSSSSSk.',
  '...kSSddddddddddSk..',
  '...kkkSSSddddSSSkk..',
  '....kk..SSSSSS..kk..',
  '....................',
  '....................',
  '....................',
  '....................',
];

/* Dirty — brown speckles */
const teenDirty0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSScSSSck.....',
  '....kSWcSSScWWSk....',
  '...kSSSWkcScWSSSk...',
  '..kSSSSSSSSSSSScSk..',
  '..kSSSppcccppSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSSwkSScSkwSSSSk.',
  '.kSSSSSScSScSSSScSk.',
  '.kSSSSSdScSSdSSSSSk.',
  '..kSddddcdcddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenDirty1: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSck.....',
  '....kSWWSSSSWWSkc...',
  '...kSSSWkSSkWSSSk...',
  '.ckSSSSSSSSSSSSSSk..',
  '..kSSSSppccppSSSSkc.',
  '.kSScSSwSSSSwSSSSSk.',
  '.kSSSSwkSScckwSSSSk.',
  '.kSSSSSccccSSSSSSSk.',
  '.kSSSSdSSccSSdSSSSk.',
  '..kSSddddddddddcSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Pet */
const teenPet0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSPPPPSSSPPPPSk...',
  '.kSSSS^^SSSS^^SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSwwwwSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenPet1: SpriteFrame = [
  '....................',
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSSkkkkSSSSk...',
  '..kSPPPPSSSPPPPSk...',
  '.kSSSS^^SSSS^^SSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSSwwwwSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* Refuse */
const teenRefuse0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkSSkk.......',
  '.....kkSSSSSSkk.....',
  '....kSWWSSSSWWSk....',
  '...kSSSXXSSXXSSSk...',
  '..kSSSSSSSSSSSSSSk..',
  '..kSSSSppSSppSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSkkSSSSSSkkSSSk.',
  '.kSSSSwwwwwwwwSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenRefuse1: SpriteFrame = [
  '....................',
  '....kk..............',
  '...kWwk.............',
  '..kkSSkk............',
  'kkSSSSSSkk..........',
  'kSWWSSSSWWSk........',
  'kSSSXXSSXXSSSk......',
  'kSSSSSSSSSSSSSSk....',
  'kSSSSppSSppSSSSk....',
  'kSSSSwSSSSwSSSSSk...',
  'kSkkSSSSSSSSkkSSk...',
  'kSwwwwwwwwwwSSSSSk..',
  '.kSSSSSdSSSSdSSSSk..',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '....................',
  '....................',
  '....................',
  '....................',
];

/* Clean */
const teenClean0: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkbbkk.......',
  '.....kkbbSSbbkk.....',
  '....kSbWSSSSWbSk....',
  '...kSSSWkSSkWSSSk...',
  '..kbbbbbbbbbbbbbbk..',
  '..kSSSSbbSSbbSSSSk..',
  '.kSSSSSwSSSSwSSSSSk.',
  '.kSSSSwkSSSSkwSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];
const teenClean1: SpriteFrame = [
  '....................',
  '.........kk.........',
  '........kWwk........',
  '.......kkbBkk.......',
  '.....kkBbBBbbkk.....',
  '....kbBWSSSSWBbk....',
  '...kBbWkSSkWbBBk...',
  '..kbbbbbbbbbbbbbbk..',
  '..kSSbbSSSSbbSSSk...',
  '.kSSSSwwSSSSwwSSSk..',
  '.kSSSSwkSSSSkwSSSSk.',
  '.kSSSSSSSSSSSSSSSSk.',
  '.kSSSSSdSSSSdSSSSSk.',
  '..kSSddddddddddSSk..',
  '..kkkSSSddddSSSkkk..',
  '...kk..SSSSSS..kk...',
  '......kk....kk......',
  '....................',
  '....................',
  '....................',
];

/* ================== animations ==================== */

export type TeenAnimationName =
  | 'idle'
  | 'happy'
  | 'eating'
  | 'playing'
  | 'sleeping'
  | 'hungry'
  | 'sad'
  | 'sick'
  | 'dirty'
  | 'pet'
  | 'refuse'
  | 'clean'
  | 'blink';

export interface TeenAnimation {
  readonly frames: readonly SpriteFrame[];
  readonly frameTime: number;
}

export const teenAnimations: Record<TeenAnimationName, TeenAnimation> = {
  idle:     { frames: [teenBase0], frameTime: 0.5 },
  happy:    { frames: [teenHappy0, teenHappy1], frameTime: 0.22 },
  eating:   { frames: [teenEat0, teenEat1], frameTime: 0.18 },
  playing:  { frames: [teenPlay0, teenPlay1, teenPlay0, teenPlay1], frameTime: 0.18 },
  sleeping: { frames: [teenSleep0, teenSleep1], frameTime: 0.6 },
  hungry:   { frames: [teenHungry0, teenHungry1], frameTime: 0.35 },
  sad:      { frames: [teenSad0, teenSad1], frameTime: 0.5 },
  sick:     { frames: [teenSick0, teenSick1], frameTime: 0.4 },
  dirty:    { frames: [teenDirty0, teenDirty1], frameTime: 0.5 },
  pet:      { frames: [teenPet0, teenPet1], frameTime: 0.28 },
  refuse:   { frames: [teenRefuse0, teenRefuse1], frameTime: 0.2 },
  clean:    { frames: [teenClean0, teenClean1], frameTime: 0.3 },
  blink:    { frames: [teenBase0], frameTime: 0.08 },
};

export const teenEyeSlots: readonly {
  readonly x: number; readonly y: number; readonly w: number; readonly h: number;
}[] = [
  { x: 7, y: 9, w: 2, h: 2 },
  { x: 12, y: 9, w: 2, h: 2 },
];

void PALETTE;
